version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: >
#      sh -c "python manage.py migrate &&
#             python manage.py collectstatic --noinput &&
#             gunicorn mycloud.wsgi:application --bind 0.0.0.0:8000"
#    volumes:
#      - ./mycloud/media:/app/media
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#    env_file:
#      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python mycloud/manage.py migrate &&
             python mycloud/manage.py collectstatic --noinput &&
             gunicorn mycloud.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./mycloud/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=mycloud.settings


  frontend:
    build:
      context: ./mycloud/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: