version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn mycloud.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./mycloud:/app
      - ./mycloud/media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=mycloud.settings


  frontend:
    build:
      context: ./mycloud/frontend
      dockerfile: Dockerfile
#    volumes:
#      - frontend_build:/app/build
    depends_on:
      - backend
#    environment:
#      - REACT_APP_API_BASE_URL=http://95.163.223.166/api
    restart: always


  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/staticfiles
      - ./mycloud/media:/app/media
      - ./mycloud/frontend/build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  frontend_build: