# Generated by Django 4.2.20 on 2025-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('size', models.IntegerField()),
                ('last_download', models.DateTimeField(blank=True, null=True)),
                ('public_link', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
    ]
